/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://iwdcicylwbhttblwjea5r2a5eq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sopqmvwrrzburbjyl24dsvhctu",
    "aws_cognito_identity_pool_id": "us-east-2:c087163b-6492-467f-8bcb-65adfce14837",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5wQdyZOQ8",
    "aws_user_pools_web_client_id": "52p4g1impslpuq52qug77mknkl",
    "oauth": {},
    "aws_cognito_login_mechanisms": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "images123529-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
